global:
  scrape_interval: 10s  # Interval between scrapes

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself

  - job_name: 'django-app'
    static_configs:
      - targets: ['django:8000']  # Replace with the service name and port of your Django app
