apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: default
spec:
  selector:
    tekton.dev/task: run-prometheus  # Update this to match your pod's labels
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
