apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
spec:
  containers:
  - name: shell
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - mountPath: /mnt/pvc
      name: config-volume
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: prometheus-config-pvc
  restartPolicy: Never
