apiVersion: v1
kind: Pod
metadata:
  name: config-writer
spec:
  initContainers:
  - name: init-writer
    image: busybox
    command: ["sh", "-c", "echo 'global:\n  scrape_interval: 10s\nscrape_configs:\n  - job_name: my_job\n    static_configs:\n      - targets: [\"localhost:9090\"]' > /mnt/pvc/prometheus.yml"]
    volumeMounts:
      - mountPath: /mnt/pvc
        name: config-volume
  containers:
  - name: main-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]  # Keeps the main container running
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: prometheus-pvc  # Use your PVC name
  restartPolicy: Never
