apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: query-prometheus-metrics
spec:
  description: "Task to query Prometheus metrics"
  params:
    - name: prometheus_url
      description: "The URL of the Prometheus server"
      type: string
      default: "http://localhost:9090"
    - name: query
      description: "Prometheus query to run"
      type: string
      default: "up"
  steps:
    - name: query-prometheus
      image: curlimages/curl:latest
      script: |
        # Query Prometheus using the provided query
        response=$(curl -s -G --data-urlencode "query=$(params.query)" $(params.prometheus_url)/api/v1/query)
        echo "Prometheus response: $response"

