apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # Change if needed
  name: config-writer-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods"]
    verbs: ["get", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-writer-rolebinding
  namespace: default  # Change if needed
subjects:
  - kind: ServiceAccount
    name: default  # Change to your specific service account if different
    namespace: default  # Change if needed
roleRef:
  kind: Role
  name: config-writer-role
  apiGroup: rbac.authorization.k8s.io
