apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-prometheus
spec:
  workspaces:
    - name: prometheus-storage
      description: "Workspace for Prometheus configuration and data"
  
  steps:
    - name: write-config
      image: busybox
      script: |
        echo -e 'global:\n  scrape_interval: 10s\n\nscrape_configs:\n  - job_name: my_job\n    static_configs:\n      - targets: ["localhost:9090"]' > /workspace/prometheus-storage/prometheus.yml

    - name: setup-prometheus
      image: prom/prometheus:latest
      command: ["sh", "-c"]
      args:
        - |
          echo "Starting Prometheus..."
          prometheus --config.file=/workspace/prometheus-storage/prometheus.yml --storage.tsdb.path=/workspace/prometheus-storage/data
